<?php /*
for more information: see languages.txt in the lang folder. 
*/
$langLoginBeforePost3  = "zalogowa&#263; si&#281; do serwera";
$langLoginBeforePost2  = "musisz najpierw ";
$langLoginBeforePost1  = "&#379;eby wys&#322;a&#263; wiadomo&#347;&#263; do Forum, ";
$langLastMsg = "Ostatnia wiadomo&#347;&#263;";
$langEditDel = "edytuj/usu&#324;";
$langSeen = "Czytane";
$langAdm = "Forum administratorów";
$langQuote = "cytuj";
$langNewTopic = "Nowy Temat";
$langAnswer = "Odpowiedz";
$langGroupSpaceLink = "Obszar grup";
$langGroupForumLink = "Forum grupy";
$langGroupDocumentsLink = "Obszar dokumentów grupy ";
$langMyGroup = "moja grupa";
$langOneMyGroups = "moja grupa";
$l_body = "Tre&#347;&#263; wiadomo&#347;ci";
$l_prevpage      = "Poprzednia strona";
$l_new           = "Nowy";
$l_enterpassword = "Musisz poda&#263; has&#322;o.";
$l_perday        = "Wiadomo&#347;ci per day";
$l_oftotal       = "of total";
$l_userdisallowed = "Nazwa u&#380;ytkownika, któr&#261; wybrano zosta&#322;a odrzucona przez administratora. Wró&#263; i spróbuj jeszcze raz.";
$l_noprivatepost  = "This is a <b>Private Forum</b>. You do not have access to post to this forum.";
$l_statsblock    = "$statsblock = \"Our users have posted a total of -$total_posts- $l_messages.<br>
We have -$total_users- Registered Users.<br>
The newest Registered User is -<a href=\\\"$profile_url\\\">$newest_user</a>-.<br>
-$users_online- \". ($users_online==1?\"user is\":\"users are\") .\" <a href=\\\"$online_url\\\">currently browsing</a> the forums.<br>\";";
$l_privnotify    = "$privnotify = \"<br>You have $new_message <a href=\\\"$privmsg_url\\\">new private \".($new_message>1?\"messages\":\"message\").\"</a>.\";";
$l_thankregister = "Thank you for registering!";
$l_alwaysdisable = "Always disable";
$l_boardlang     = "Board Language";
$l_topicreview   = "Przegl±d Tematów";
$l_pwdmessage = "Dear $checkinfo[username],
You are receiving this email because you (or someone pretending to be you)
has requested a passwordchange on $sitename forums. If you believe you have
received this message in error simply delete it and your password will remain
the same.

Your new password as generated by the forums is: $newpw

In order for this change to take effect you must visit this page:

   http://$SERVER_NAME$PHP_SELF?actkey=$key

Once you have visited the page your password will be changed in our database,
and you may login to the profile section and change it as desired.

Thank you for using $sitename Forums

$email_sig";
$l_forum = "Forum dyskusyjne";
$l_forums = "Fora dyskusyjne - Kategorie";
$l_topic = "Temat";
$l_topics = "Tematy";
$l_replies = "Odpowiedzi";
$l_poster = "Wys&#322;a&#322;";
$l_author = "Autor";
$l_views = "Czytane";
$l_post = "list";
$l_posts = "Listy";
$l_message = "wiadomo¶æ";
$l_messages = "Wiadomo¶ci";
$l_subject = "Temat";
$l_from = "Od";
$l_moderator = "Moderator";
$l_username = "Nazwa u&#380;ytkownika";
$l_password = "Has&#322;o";
$l_email = "Email";
$l_emailaddress = "Adres email";
$l_preferences = "Preferencje";
$l_anonymous = "Anonim";
$l_guest = "Go¶æ";
$l_noposts = "Nr Listy";
$l_joined = "Po&#322;&#261;czony";
$l_gotopage = "Id&#378; do strony";
$l_nextpage = "Nast&#281;pna strona";
$l_go = "Id&#378;";
$l_selectforum = "Wybierz Forum dyskusyjne";
$l_date = "Data";
$l_number = "Number";
$l_name = "Nazwa";
$l_options = "Opcje";
$l_submit = "Wy&#347;lij";
$l_confirm = "Potwierd&#378;";
$l_enter = "Wej&#347;cie";
$l_by = " przez";
$l_ondate = "on";
$l_html = "HTML";
$l_bbcode = "BBcode";
$l_smilies = "Smilies";
$l_on = "On";
$l_off = "Off";
$l_yes = "Tak";
$l_no = "Nie";
$l_click = "Kliknij";
$l_here = "tutaj";
$l_toreturn = "&#379;eby powróci&#263;";
$l_returnindex = "&#380;eby powróci&#263; do spisu Forów dyskusyjnych";
$l_returntopic = "&#380;eby powróci&#263; do spisu tematów.";
$l_error = "B&#322;&#261;d";
$l_tryagain = "Wró&#263; i spróbuj jeszcze raz.";
$l_mismatch = "Passwords do not match.";
$l_userremoved = "This user has been removed from the User database";
$l_wrongpass = "You entered the wrong password.";
$l_userpass = "Please enter your username and password.";
$l_banned = "You have been banned from this forum. Contact the system administrator if you have any questions.";
$l_nopost = "Brak dost&#281;pu do listów w tym Forum.";
$l_noread = "You do not have access to read this forum.";
$l_lastpost = "Ostatni list";
$l_sincelast = "since your last visit";
$l_newposts = "New Listy since your last visit";
$l_nonewposts = "No New Listy since your last visit";
$l_indextitle = "Lista Forów dyskusyjnych";
$l_profile = "Profile";
$l_register = "Register";
$l_onlyreq = "Only requried if being changed";
$l_location = "From";
$l_viewpostuser = "View posts by this user";
$l_url = "URL";
$l_icq = "ICQ";
$l_icqnumber = "ICQ Number";
$l_icqadd = "Add";
$l_icqpager = "Pager";
$l_aim = "AIM";
$l_yim = "YIM";
$l_yahoo = "Yahoo Messenger";
$l_msn = "MSN";
$l_messenger = "MSN Messenger";
$l_website = "Web Site Address";
$l_occupation = "Occupation";
$l_interests = "Interests";
$l_signature = "Signature";
$l_sigexplain = "This is a block of text that can be added to posts you make.<BR>255 characters max!";
$l_usertaken = "The Nazwa u¿ytkownika you picked has been taken.";
$l_infoupdated = "Your Information has been updated";
$l_publicmail = "Allow other users to view my Adres email";
$l_itemsreq = "Items marked with a * are required";
$l_viewforum = "View Forum";
$l_notopics = "Nie ma &#380;adnych tematów w tym Forum. Mo&#380;esz napisa&#263; now&#261; wiadomo&#347;&#263;.";
$l_hotthres = "More then  Listy";
$l_islocked = "Temat is Locked (No new Listy may be made in it)";
$l_moderatedby = "Moderated by";
$l_privateforum = "This is a <b>Private Forum</b>.";
$l_private = "This is a <b>Private Forum</b>.<br>Note: you must have cookies enabled in order to use private forums.";
$l_topictitle = "View Temat";
$l_unregistered = "Unregistered User";
$l_posted = "Posted";
$l_profileof = "View Profile of";
$l_viewsite = "Goto the website of";
$l_icqstatus = "ICQ status";
$l_editdelete = "Edit/Delete This list";
$l_replyquote = "Reply with quote";
$l_viewip = "View Posters IP (Moderators/Admins Only)";
$l_locktopic = "Lock this Temat";
$l_unlocktopic = "Unlock this Temat";
$l_movetopic = "Move this Temat";
$l_deletetopic = "Delete this Temat";
$l_loggedinas = "Logged in as";
$l_notloggedin = "Not logged in";
$l_logout = "Logout";
$l_login = "Login";
$l_separator = "» »";
$l_editprofile = "Edit Profile";
$l_editprefs = "Edit Your Preferencje";
$l_search = "Search";
$l_memberslist = "Memberslist";
$l_faq = "FAQ";
$l_privmsgs = "Private Wiadomo¶ci";
$l_sendpmsg = "Send a Private Message";
$l_adminpanel = "Administration Panel";
$l_poweredby = "Powered by";
$l_version = "Version";
$l_notfilledin = "Error - you did not fill in all the required fields.";
$l_invalidname = "The username you chose \"\" has been taken.";
$l_disallowname = "The username you chose, \"\" has been disallowed by the administrator.";
$l_welcomesubj = "Welcome to  Forums";
$l_welcomemail = "
Welcome to  Forums,

Please keep this email for your records.


Your account information is as follows:

----------------------------
Username: 
Password: 
----------------------------

Please do not forget your password as it has been encrypted in our database and we cannot retrieve it for you.
However, should you forget your password we provide an easy to use script to generate and email a new, random, password.

Thank you for registering.


";
$l_beenadded = "You have been added to the database.";
$l_useruniq = "Must be unique. No two users can have the same Username.";
$l_storecookie = "Store my username in a cookie for 1 year.";
$l_prefupdated = "Preferencje zaktualizowane. Kliknij <a href=\"index.\">tutaj</a> &#380;eby powróci&#263; do spisu Forów dyskusyjnych";
$l_themecookie = "NOTE: In order to use themes you MUST have cookies enabled.";
$l_alwayssig = "Always attach my signature";
$l_alwayssmile = "Always disable Smilies";
$l_alwayshtml = "Always disable HTML";
$l_alwaysbbcode = "Always disable BBcode";
$l_boardtheme = "Board Theme";
$l_nothemes = "No Themes In database";
$l_saveprefs = "Save Preferencje";
$l_searchterms = "Keywords";
$l_searchany = "Search for ANY of the terms (Default)";
$l_searchall = "Search for ALL of the terms";
$l_searchallfrm = "Search All Forums";
$l_sortby = "Sort by";
$l_searchin = "Search in";
$l_titletext = "Title & Text";
$l_nomatches = "No records match that query. Please broaden your search.";
$l_whosonline = "Who\'s online?";
$l_nousers = "No Users are currently browsing the forums";
$l_notedit = "You can\'t edit a post that isn\'t yours.";
$l_permdeny = "You did not supply the correct Has³o or do not have permission to edit this post. Wróæ i spróbuj jeszcze raz.";
$l_editedby = "This wiadomo¶æ was edited by:";
$l_stored = "Twoja wiadomo&#347;&#263; zosta&#322;a zapisana w bazie danych.";
$l_viewmsg = "&#380;eby zobaczy&#263; wiadomo&#347;&#263;.";
$l_deleted = "Your list has been deleted.";
$l_nouser = "Ta nazwa u&#380;ytkownika nie istnieje.";
$l_passwdlost = "I forgot my password!";
$l_delete = "Usu&#324; wiadomo&#347;&#263;";
$l_disable = "Disable";
$l_onthispost = "on this Post";
$l_htmlis = "HTML is";
$l_bbcodeis = "BBcode is";
$l_notify = "Notify by email when replies are posted";
$l_emptymsg = "Musisz wpisa&#263; wiadomo&#347;&#263; aby wys&#322;a&#263;. Nie mo&#380;esz wys&#322;a&#263; pustej wiadomo&#347;ci.";
$l_aboutpost = "About Posting";
$l_regusers = "All <b>Registered</b> users";
$l_anonusers = "<b>Anonymous</b> users";
$l_modusers = "Only <B>Moderators and Administrators</b>";
$l_anonhint = "<br>(To post anonymously simply do not enter a username and password)";
$l_inthisforum = "can post new topics and replies to this forum";
$l_attachsig = "Show signature <font size=-2>(This can be altered or added in your profile)</font>";
$l_cancelpost = "Zrezygnuj";
$l_nopostlock = "You cannot post a reply to this topic, it has been locked.";
$l_notifysubj = "A reply to your topic has been posted.";
$l_notifybody = "Dear $m[username]\\r\\nYou are receiving this Email because a message
you posted on $sitename forums has been replied to, and
you selected to be notified on this event.

You may view the topic at:

http://$SERVER_NAME$url_phpbb/viewtopic.$phpEx?topic=$topic&forum=$forum

Or view the $sitename forum index at

http://$SERVER_NAME$url_phpbb

Thank you for using $sitename forums.

Have a nice day.

$email_sig";
$l_norecipient = "You must enter the username you want to send the wiadomo¶æ to.";
$l_sendothermsg = "Send another Private Message";
$l_cansend = "mo&#380;na wysy&#322;a&#263; wiadomo&#347;ci prywatne";
$l_yourname = "Twoja Nazwa u&#380;ytkownika";
$l_recptname = "Nazwa u&#380;ytkownika Odbiorcy";
$l_pmposted = "Reply Posted, you can click <a href=\"viewpmsg.\">here</a> to view your Private Wiadomo¶ci";
$l_nopmsgs = "Nie masz &#380;adnych Wiadomo&#347;ci prywatnych.";
$l_reply = "Reply";
$l_deletesucces = "Deletion successful.";
$l_smilesym = "What to type";
$l_smileemotion = "Emotion";
$l_smilepict = "Picture";
$l_wrongactiv = "The activation key you provided is not correct. Please check email wiadomo¶æ you recived and make sure you have copied the activation key exactly.";
$l_passchange = "Your password has been successfully changed. You may now goto your <a href=\"bb_profile.?mode=edit\">profile</a> and change your password to a more suitable one.";
$l_wrongmail = "The email address you entered does not match the one stored in our database.";
$l_passsubj = " Forums Password Change";
$l_passsent = "Your password has changed to a new, random, password. Please check your email on how to complete the password change procedure.";
$l_emailpass = "Email Lost Password";
$l_passexplain = "Please fill out the form, a new password will be sent to your Email address";
$l_sendpass = "Send Password";
$langHelp = "Help";
$langLastMsgs = "Ostatnia wiadomo&#347;&#263;";
$l_quotemsg = "Wiadomo&#347;&#263;";
$lang_mail_notification_title = "odpowiedz na temat:";
$lang_mail_notification_captatio = "Szanowna/y";
$lang_mail_notification_hasreplied = "odpowiedzia&#322;(-a) na wiadomo&#347;&#263; z forum";
$lang_mail_notification_ofcourse = "kursu";
$lang_mail_notification_informed = "Wyrazi&#322;e&#347;(-&#322;a&#347;) ch&#281;&#263; bycia informowanym(-n&#261;) o odpowiedziach na t&#281; wiadomo&#347;&#263; z forum.";
$lang_mail_notification_yesiwant = "Tak, chcê otrzymywaæ odpowiedzi przez e-mail";
$lang_reply_this_message = "Odpowiedz na t&#281; wiadomo&#347;&#263;";
$lang_author = "Autor";
$lang_threaded_view = "Widok przewini&#281;ty";
$lang_flat_view = "Widok p&#322;aski";
$lang_lock = "Zamknij";
$lang_unlock = "Otwórz";
$lang_locked = "zamkni&#281;te";
$lang_edit_post = "Edytuj post\'a";
$lang_new_topic = "Nowy temat";
$lang_post_new_topic_in = "Nowy temat w";
$langLock = "Zamknij";
?>