<?php /*
for more information: see languages.txt in the lang folder. 
*/
$langLoginBeforePost3  = "login på E-learning";
$langLoginBeforePost2  = "skal du først ";
$langLoginBeforePost1  = "For at kunne indsende et indlæg til diskussionsforum, ";
$langLastMsg = "Sidste indlæg";
$langEditDel = "Rediger/slet";
$langSeen = "Set";
$langAdm = "Administration af Forum";
$langQuote = "citere";
$langNewTopic = "Nyt emne";
$langAnswer = "Svar";
$langGroupSpaceLink = "Gruppe område";
$langGroupForumLink = "Gruppeforum";
$langGroupDocumentsLink = "Gruppedokumenter ";
$langMyGroup = "min gruppe";
$langOneMyGroups = "mit tilsyn";
$l_body = "Indhold i indlæg";
$l_prevpage      = "Forrige side";
$l_new           = "Ny";
$l_enterpassword = "Du skal skrive din adgangskode.";
$l_perday        = "beskeder per dag";
$l_oftotal       = "af alle";
$l_userdisallowed = "Det valgte brugernavn tillades ikke af administrator. Prøv igen";
$l_noprivatepost  = "Lukket forum du har ikke adgang til at sende indlæg til dette forum.";
$l_statsblock    = "$statsblock = \"Vores deltagere har indsendt i alt -$total_posts- $l_messages.<br>
Vi har -$total_users- Registrerede deltagere.<br>
Sidste nye registrerede deltager er -<a href=\\\"$profile_url\\\">$newest_user</a>-.<br>
-$users_online- \". ($users_online==1?\"deltager er\":\"deltagerne er\") .\" <a href=\\\"$online_url\\\">browser lige nu</a> diskussionsforum.<br>\";";
$l_privnotify    = "$privnotify = \"<br>Du har $new_message <a href=\\\"$privmsg_url\\\">ny privat \".($new_message>1?\"besked\":\"besked\").\"</a>.\";";
$l_thankregister = "Tak for din registrering!";
$l_alwaysdisable = "Deaktiver altid";
$l_boardlang     = "Board Language";
$l_topicreview   = "Emne gennemgang";
$l_pwdmessage = "Kære $checkinfo[username],
Du får denne email fordi du (eller en som skal forestille at være dig)
har sendt en forespørgsel på ændring af adgangskoden på $sitename forum. Har du fået denne besked ved en fejl,
slet den og din adgangskode vil forblive den samme.

Your new password as generated by the forums is: $newpw

In order for this change to take effect you must visit this page:

   http://$SERVER_NAME$PHP_SELF?actkey=$key

Once you have visited the page your password will be changed in our database,
and you may login to the profile section and change it as desired.

Thank you for using $sitename Forums

$email_sig";
$l_forum = "Diskussionsforum";
$l_forums = "Diskussionsforum";
$l_topic = "Emne";
$l_topics = "Emner";
$l_replies = "Svar";
$l_poster = "Lagt ud af";
$l_author = "Forfatter";
$l_views = "Se";
$l_post = "Indlæg";
$l_posts = "Indlæg";
$l_message = "besked";
$l_messages = "beskeder";
$l_subject = "Emne";
$l_from = "Fra";
$l_moderator = "Moderator";
$l_username = "Brugernavn";
$l_password = "Adgangskode";
$l_email = "Email";
$l_emailaddress = "Emailaddresse";
$l_preferences = "Præferencer";
$l_anonymous = "Anonym";
$l_guest = "Gæst";
$l_noposts = "Ingen indlæg";
$l_joined = "Joined";
$l_gotopage = "Gå til side";
$l_nextpage = "Næste side";
$l_go = "Gå";
$l_selectforum = "Vælg et Diskussionsforum";
$l_date = "Dato";
$l_number = "Antal";
$l_name = "Navn";
$l_options = "Valg";
$l_submit = "Send";
$l_confirm = "Bekræft";
$l_enter = "Indskriv";
$l_by = "af";
$l_ondate = "på";
$l_html = "HTML";
$l_bbcode = "BBcode";
$l_smilies = "Smilies";
$l_on = "On";
$l_off = "Off";
$l_yes = "Ja";
$l_no = "Nej";
$l_click = "Klik";
$l_here = "her";
$l_toreturn = "retur";
$l_returnindex = "Retur til forum index";
$l_returntopic = "Retur til forum emnelisten.";
$l_error = "Fejl";
$l_tryagain = "Venligst gå tilbage og prøv igen.";
$l_mismatch = "Adgangskoder matcher ikke.";
$l_userremoved = "Denne deltager er blevet fjernet fra deltagerdatabasen";
$l_wrongpass = "Du indskrev den forkerte adgangskode.";
$l_userpass = "Venligst skriv dit brugernavn og adgangskode.";
$l_banned = "Du er blevet udelukket af dette forum. Kontakt systemadministrator hvis du har spørgsmål.";
$l_nopost = "Du har ikke adgang til at sende indlæg til dette forum.";
$l_noread = "Du har ikke adgang til at læse i dette forum.";
$l_lastpost = "Sidste indlæg";
$l_sincelast = "siden dit sidste besøg";
$l_newposts = "Nyt indlæg siden sidste besøg";
$l_nonewposts = "Ingen nye indlæg siden sidste besøg";
$l_indextitle = "Forum index";
$l_profile = "Profil";
$l_register = "Registrer";
$l_onlyreq = "Kun nødvendig hvis det er ændret";
$l_location = "Fra";
$l_viewpostuser = "Se indlæg af denne deltager";
$l_url = "URL";
$l_icq = "ICQ";
$l_icqnumber = "ICQ Number";
$l_icqadd = "Tilføj";
$l_icqpager = "Pager";
$l_aim = "AIM";
$l_yim = "YIM";
$l_yahoo = "Yahoo Messenger";
$l_msn = "MSN";
$l_messenger = "MSN Messenger";
$l_website = "Website Adresse";
$l_occupation = "Stilling";
$l_interests = "Interesser";
$l_signature = "Underskrift";
$l_sigexplain = "Dette er en tekstblok som kan tilføjes det indlæg du udarbejder.<BR>Højst 255 karakterer!";
$l_usertaken = "Brugernavnet du har valgt er taget af en anden.";
$l_infoupdated = "Din information er blevet opdateret";
$l_publicmail = "Tillad andre deltagere at se min Emailaddresse";
$l_itemsreq = "Poster markeret med en * er obligatoriske";
$l_viewforum = "Se Forum";
$l_notopics = "Der er ingen emner til dette forum. Du kan indsende et.";
$l_hotthres = "More then  Indlæg";
$l_islocked = "Emnet er lukket (Ingen nye indlæg må lægges ind)";
$l_moderatedby = "Modereret af";
$l_privateforum = "Dette er <b>Lukket Forum</b>.";
$l_private = "Lukket forum<br>Bemærk: Du skal have en cookie for at kunne bruge et lukket forum.";
$l_topictitle = "Se emne";
$l_unregistered = "Ikke-registreret deltager";
$l_posted = "Lagt ud";
$l_profileof = "Se profil af";
$l_viewsite = "Gå til website af";
$l_icqstatus = "ICQ status";
$l_editdelete = "Rediger/Slet dette indlæg";
$l_replyquote = "Svar med citat";
$l_viewip = "Se bidragsyderens IP (Moderator/Admin kun)";
$l_locktopic = "Lås dette Emne";
$l_unlocktopic = "Åben ette Emne";
$l_movetopic = "Flyt denne Emne";
$l_deletetopic = "Slet dette Emne";
$l_loggedinas = "Logget på som";
$l_notloggedin = "Ikke logget ind";
$l_logout = "Logout";
$l_login = "Login";
$l_separator = " > ";
$l_editprofile = "Rediger profil";
$l_editprefs = "Rediger dine Præferencer";
$l_search = "Søg";
$l_memberslist = "Medlemsliste";
$l_faq = "FAQ";
$l_privmsgs = "Private beskeder";
$l_sendpmsg = "Send en Privat besked";
$l_adminpanel = "Administrationspanel";
$l_poweredby = "Udviklet af";
$l_version = "Version";
$l_notfilledin = "Fejl - du udfyldte ikke alle obligatoriske felter.";
$l_invalidname = "Brugernavnet som du valgte \"\" er optaget.";
$l_disallowname = "Brugernavnet du valgte, \"\" er ikke tilladt af administrator.";
$l_welcomesubj = "Velkommen til  Forum";
$l_welcomemail = "
Velkommen til  Forum,

Please keep this email for your records.


Your account information is as follows:

----------------------------
Username: 
Password: 
----------------------------

Please do not forget your password as it has been encrypted in our database and we cannot retrieve it for you.
However, should you forget your password we provide an easy to use script to generate and email a new, random, password.

Thank you for registering.


";
$l_beenadded = "Du er blevet tilføjet databasen.";
$l_useruniq = "Skal være unik. To deltagere kan ikke have samme brugernavn.";
$l_storecookie = "Gem mit brugernavn i en cookie i et år.";
$l_prefupdated = "Præferencer opdateret. Klik <a href=\"index.\">her</a> Retur til forum index";
$l_themecookie = "Bemærk: For at kunne bruge temaer skal du have oprettet cookies.";
$l_alwayssig = "Tilføj altid min underskrift";
$l_alwayssmile = "Deaktiver altid Smilies";
$l_alwayshtml = "Deaktiver altid HTML";
$l_alwaysbbcode = "Deaktiver altid BBcode";
$l_boardtheme = "Board Theme";
$l_nothemes = "Ingen temaer i databasen";
$l_saveprefs = "Gem Præferencer";
$l_searchterms = "Nøgleord";
$l_searchany = "Søg efter ethvert af ordene (Standard)";
$l_searchall = "Søg efter alle ordene";
$l_searchallfrm = "Søg alle fora";
$l_sortby = "ordnet efter";
$l_searchin = "Søg i";
$l_titletext = "Titel & Tekst";
$l_nomatches = "Ingen optegnelser matcher denne forespørgsel. Venligst udvid din søgning.";
$l_whosonline = "Hvem er online?";
$l_nousers = "Ingen deltagere browser i øjeblikket foraene";
$l_notedit = "Du kan ikke redigere et indlæg som ikke er dit.";
$l_permdeny = "Du har ikke anført din korrekte Adgangskode eller du har ikke tilladelse til at redigere dette indlæg. Venligst gå tilbage og prøv igen.";
$l_editedby = "Denne besked var redigeret af:";
$l_stored = "Din besked er blevet gemt i databasen.";
$l_viewmsg = "for at se din besked.";
$l_deleted = "Dit Indlæg er blevet slettet.";
$l_nouser = "Dette Brugernavn eksisterer ikke.";
$l_passwdlost = "Jeg har glemt min adgangskode!";
$l_delete = "Slet dette indlæg";
$l_disable = "Deaktiver";
$l_onthispost = "på dette indlæg";
$l_htmlis = "HTML er";
$l_bbcodeis = "BBcode er";
$l_notify = "Gør opmærksom vha. email når der er svar";
$l_emptymsg = "Du skal skrive en besked som skal sendes. Du kan ikke sende en tom besked.";
$l_aboutpost = "Om at sende";
$l_regusers = "Alle <b>Registrerede</b> brugere";
$l_anonusers = "<b>Anonyme</b> brugere";
$l_modusers = "Kun <B>Moderatorere og Administratorere</b>";
$l_anonhint = "<br>(For at kunne sende anonymt skal du undlade at anføre et brugernavn og en adgangskode)";
$l_inthisforum = "kan sende nye emner og svar til dette forum";
$l_attachsig = "Vis underskrift <font size=-2>(Denne kan ændres eller tilføjes i din profil)</font>";
$l_cancelpost = "Fortryd indlæg";
$l_nopostlock = "Du kan ikke sende et svar til dette indlæg, det er blevet låst.";
$l_notifysubj = "Et svar på dit indlæg er blevet indsendt.";
$l_notifybody = "Kære $m[username]\\r\\nDu får denne Email, fordi der er indkommet
et svar på det indlæg, du lagde ud på $sitename forum, og du ville gerne gøres 
opmærksom på dette, når det skete.


You may view the topic at:

http://$SERVER_NAME$url_phpbb/viewtopic.$phpEx?topic=$topic&forum=$forum

Or view the $sitename forum index at

http://$SERVER_NAME$url_phpbb

Thank you for using $sitename forums.

Have a nice day.

$email_sig";
$l_norecipient = "Du skal anføre brugernavnet som du ønsker at sende beskeden til.";
$l_sendothermsg = "Send en anden privat besked";
$l_cansend = "kan sende Private beskeder";
$l_yourname = "Dit Brugernavn";
$l_recptname = "Modtagerens Brugernavn";
$l_pmposted = "Svar sendt, du kan klikke <a href=\"viewpmsg.\">here</a> for at se dine Private beskeder";
$l_nopmsgs = "Du har ingen Private beskeder.";
$l_reply = "Svar";
$l_deletesucces = "Slettet med succes.";
$l_smilesym = "Hvad skal skrives";
$l_smileemotion = "Ekspressiv Web-bevægelse (Emotion)";
$l_smilepict = "Billede";
$l_wrongactiv = "Aktiveringsnøglen er ikke koorekt udstyret. Venligst kontroller email besked du modtog og vær sikker på, at du har kopieret aktiveringsnøglen korrekt.";
$l_passchange = "Din adgangskode er ændret med succes. Du kan nu gå til din <a href=\"bb_profile.?mode=edit\">profil</a> og ændre din adgangskode til en selvvalgt.";
$l_wrongmail = "Den anførte email matcher ikke en i databasen.";
$l_passsubj = " Forum Adgangskode Ændre";
$l_passsent = "Din adgangskode er blevet ændret til en ny tilfældig. Venligst kontroller i din email, hvordan du fuldfører processen med din nye ændrede adgangskode.";
$l_emailpass = "Email Glemt Adgangskode";
$l_passexplain = "Venligst udfyld formularen, en ny adgangskode vil blive tilsendt din Emailadresse";
$l_sendpass = "Send Adgangskode";
$langHelp = "Hjælp";
$langLastMsgs = "Sidste besked";
$l_quotemsg = "[quote]\\nOn $m[post_time], $m[username] wrote:\\n$text\\n[/quote]";
$lang_mail_notification_title = "svar på emnet:";
$lang_mail_notification_captatio = "Kære";
$lang_mail_notification_hasreplied = "har besvaret en forum besked";
$lang_mail_notification_ofcourse = "for kurset";
$lang_mail_notification_informed = "Du angav at du ønskede at blive informeret om svar på denne forum besked.";
$lang_mail_notification_yesiwant = "Ja, jeg ønsker at blive informeret via e-mail (".$_user['mail'].") når et svar bliver postet";
$lang_reply_this_message = "Svar på denne besked";
$lang_author = "Forfatter";
$lang_threaded_view = "Tråd-visning";
$lang_flat_view = "Flad visning";
$lang_lock = "Lås";
$lang_unlock = "Lås op";
$lang_locked = "låst";
$lang_edit_post = "Rediger postering";
$lang_new_topic = "Nyt emne";
$lang_post_new_topic_in = "Nyt emne i";
$langLock = "Lås";
$langPostNewTopic = "Post et nyt emne";
?>