<?php
# DOKEOS version Dokeos LCMS 0.3
# File generated by /install/index.php script - Wed, 05 Dec 2007 16:03:38 +0100
/*
==============================================================================
	Dokeos - elearning and course management software

	Copyright (c) 2004-2005 Dokeos S.A.
	Copyright (c) 2003 Ghent University (UGent)
	Copyright (c) 2001 Universite catholique de Louvain (UCL)

	For a full list of contributors, see "credits.txt".
	The full license can be read in "license.txt".

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	See the GNU General Public License for more details.

	Contact address: Dokeos, 44 rue des palais, B-1030 Brussels, Belgium
	Mail: info@dokeos.com
==============================================================================
*/
/*
==============================================================================
		Configuration of virtual campus

This file contains a list of variables that can be modified by the campus
site administrator. Pay attention when changing these variables, some changes
can cause Dokeos to stop working.
If you changed some settings and want to restore them, please have a look at
claro_main.conf.dist.php. That file is an exact copy of the config file at
install time.
==============================================================================
*/

//============================================================================
//   MYSQL connection settings
//============================================================================
// Your MySQL server
$dbHost         = 'localhost';
// Your MySQL username
$dbLogin        = 'root';
// Your MySQL password
$dbPass         = '';

//============================================================================
//   Database settings
//============================================================================
// is tracking enabled?
$is_trackingEnabled = true;
// is single database enabled (DO NOT MODIFY THIS)
$singleDbEnabled    = false;
// prefix for course tables (IF NOT EMPTY, can be replaced by another prefix,
// else leave empty)
$courseTablePrefix      = '';
// separator between database and table name (DO NOT MODIFY THIS)
$dbGlu                  = '`.`';
// prefix all created bases (for courses) with this string
$dbNamePrefix           = 'dokeos_';
// main Dokeos database
$mainDbName             = 'dokeos_main';
// stats Dokeos database
$statsDbName            = 'dokeos_stats';
// scorm Dokeos database
$scormDbName            = 'dokeos_scorm';

//============================================================================
//   Directory settings
//============================================================================
// URL to the root of your Dokeos installation
$rootWeb                     = 'http://localhost/dokeoslcms/';
// Path to the root of your Dokeos installation
$rootSys                     = dirname(__FILE__).'/../../../';
// Path from your WWW-root to the root of your Dokeos installation
$urlAppend                   = '/dokeos';
// Directory of the Dokeos code
$clarolineRepositoryAppend   = "main/";
// Directory to store all course-related files
$coursesRepositoryAppend     = "courses/";
// Directory of the admin-area
$rootAdminAppend             = "admin/";
// Do not change the following values
$clarolineRepositorySys      = $rootSys.$clarolineRepositoryAppend;
$clarolineRepositoryWeb      = $rootWeb.$clarolineRepositoryAppend;
$coursesRepositorySys        = $rootSys.$coursesRepositoryAppend;
$coursesRepositoryWeb        = $rootWeb.$coursesRepositoryAppend;
$rootAdminSys                = $clarolineRepositorySys.$rootAdminAppend;
$rootAdminWeb                = $clarolineRepositoryWeb.$rootAdminAppend;
// directory to store archived courses
$archiveDirName              = "archive";
// change this to a place out of web if you can
$garbageRepositorySys        = '/';
// URL to your phpMyAdmin installation.
// If not empty, a link will be available in the Platform Administration
$phpMyAdminPath              = '';

//============================================================================
//   Login modules settings
//============================================================================
// For new login module
// Uncomment these lines to activate ldap
// $extAuthSource["ldap"]["login"]=$clarolineRepositorySys."auth/ldap/login.php";
// $extAuthSource["ldap"]["newUser"]=$clarolineRepositorySys."auth/ldap/newUser.php";

//============================================================================
//   Language settings
//============================================================================
// Available Languages : look at the "lang" directory
$platformLanguage   = 'english';
$language           = $platformLanguage;

//============================================================================
//   Misc. settings
//============================================================================
// Dokeos version
$dokeos_version   = 'Dokeos LCMS 0.3';
// Verbose backup
$verboseBackup      = false;
// security word for password recovery
$security_key       = '6285093549597fc29e98114506719e56';
// light grey
$color1 = "#F5F5F5";
// less light grey for bicolored tables, also used in forums, groups etc.
$color2 = "#E6E6E6";
// Settings for new and future features
$userPasswordCrypted          = true;
// You may have to restart your web server if you change this
$storeSessionInDb             = false;

//============================================================================
//   Plugin settings
//============================================================================
// plugins arrays
$plugins["main_menu"]        = array();
$plugins["main_menu_logged"] = array();
$plugins["banner"]           = array();
// To load a new plugin, add a line like this
//     $plugins["main_menu"][] = "my_plugin";
// where "my_plugin" is the directory where your plugin is in folder "plugin"
// main_menu_logged is the same as main_menu for when a user is logged in
?>