#!/bin/sh

cd commandlinemigration
./userscommandlinemigration.php
./personalagendascommandlinemigration.php
./systemsettingscommandlinemigration.php
./classescommandlinemigration.php
./coursescommandlinemigration.php
./metadatacommandlinemigration.php
./groupscommandlinemigration.php
./announcementscommandlinemigration.php
./calendareventscommandlinemigration.php
./documentscommandlinemigration.php
./linkscommandlinemigration.php
./dropboxescommandlinemigration.php
./forumscommandlinemigration.php
./learningpathscommandlinemigration.php
./quizzescommandlinemigration.php
./studentpublicationscommandlinemigration.php
./surveyscommandlinemigration.php
./scormscommandlinemigration.php
./assignmentscommandlinemigration.php
./userinfoscommandlinemigration.php
cd ..