cd commandlinemigration

@C:\wamp\bin\php\php5.2.5\php.exe userscommandlinemigration.php
@C:\wamp\bin\php\php5.2.5\php.exe personalagendascommandlinemigration.php
@C:\wamp\bin\php\php5.2.5\php.exe systemsettingscommandlinemigration.php
@C:\wamp\bin\php\php5.2.5\php.exe classescommandlinemigration.php
@C:\wamp\bin\php\php5.2.5\php.exe coursescommandlinemigration.php
@C:\wamp\bin\php\php5.2.5\php.exe metadatacommandlinemigration.php
@C:\wamp\bin\php\php5.2.5\php.exe groupscommandlinemigration.php
@C:\wamp\bin\php\php5.2.5\php.exe announcementscommandlinemigration.php
@C:\wamp\bin\php\php5.2.5\php.exe calendareventscommandlinemigration.php
@C:\wamp\bin\php\php5.2.5\php.exe documentscommandlinemigration.php
@C:\wamp\bin\php\php5.2.5\php.exe linkscommandlinemigration.php
@C:\wamp\bin\php\php5.2.5\php.exe dropboxescommandlinemigration.php
@C:\wamp\bin\php\php5.2.5\php.exe forumscommandlinemigration.php
@C:\wamp\bin\php\php5.2.5\php.exe learningpathscommandlinemigration.php
@C:\wamp\bin\php\php5.2.5\php.exe quizzescommandlinemigration.php
@C:\wamp\bin\php\php5.2.5\php.exe studentpublicationscommandlinemigration.php
@C:\wamp\bin\php\php5.2.5\php.exe surveyscommandlinemigration.php
@C:\wamp\bin\php\php5.2.5\php.exe scormscommandlinemigration.php
@C:\wamp\bin\php\php5.2.5\php.exe assignmentscommandlinemigration.php
@C:\wamp\bin\php\php5.2.5\php.exe userinfoscommandlinemigration.php
@C:\wamp\bin\php\php5.2.5\php.exe trackerscommandlinemigration.php
cd ..