<?php /*
for more information: see languages.txt in the lang folder. 
*/
$langLoginBeforePost3  = "ล็อคอินเข้าระบบก่อน";
$langLoginBeforePost2  = "คุณต้อง ";
$langLoginBeforePost1  = "ต้องการเขียนกระทู้บนกระดานข่าวนี้ ";
$langLastMsg = "โพสครั้งล่าสุด";
$langEditDel = "แก้ไข/ลบ";
$langSeen = "อ่าน";
$langAdm = "admin";
$langQuote = "quote";
$langNewTopic = "ตั้งกระทู้ใหม่";
$langAnswer = "ตอบกระทู้";
$langGroupSpaceLink = "Group area";
$langGroupForumLink = "Forum of group";
$langGroupDocumentsLink = "Documents of the group ";
$langMyGroup = "my group";
$langOneMyGroups = "my supervision";
$l_body = "Message Body";
$l_prevpage      = "หน้าที่แล้ว";
$l_new           = "ใหม่";
$l_enterpassword = "คุณต้องพิมพ์รหัสผ่าน";
$l_perday        = "ข้อความ per day";
$l_oftotal       = "จากทั้งหมด ";
$l_userdisallowed = "๊Username ที่คุณเลือก ถูกสงวนไว้สำหรับผู้ควบคุมระบบ กรุณาลองใหม่อีกครั้ง";
$l_noprivatepost  = "นี้เป็น <b>กระดานส่วนตัว</b>. คุณไม่ได้รับสิทธิ์ให้เข้าไปส่งข้อความในกระดานข่าวนี้";
$l_statsblock    = "$statsblock = \"สมาชิกของเราโพสข้อความไว้ทั้งหมด -$total_posts- $l_messages.<br>
เรามี -$total_users- สมาชิกที่ลงทะเบียน<br>
สมาชิกผู้ลงทะเบียนใหม่ล่าสุดคือ -<a href=\\\"$profile_url\\\">$newest_user</a>-.<br>
-$users_online- \". ($users_online==1?\"user is\":\"users are\") .\" <a href=\\\"$online_url\\\">currently browsing</a> the forums.<br>\";";
$l_privnotify    = "$privnotify = \"<br>ท่านมี $new_message <a href=\\\"$privmsg_url\\\">ข้อความส่วนตัว \".($new_message>1?\"messages\":\"message\").\"</a>.\";";
$l_thankregister = "ขอบคุณที่ลงทะเบียน!";
$l_alwaysdisable = "Always disable";
$l_boardlang     = "ภาษา";
$l_topicreview   = "รายการกระทู้";
$l_pwdmessage = "Dear $checkinfo[username],
You are receiving this email because you (or someone pretending to be you)
has requested a passwordchange on $sitename forums. If you believe you have
received this message in error simply delete it and your password will remain
the same.

Your new password as generated by the forums is: $newpw

In order for this change to take effect you must visit this page:

   http://$SERVER_NAME$PHP_SELF?actkey=$key

Once you have visited the page your password will be changed in our database,
and you may login to the profile section and change it as desired.

Thank you for using $sitename Forums

$email_sig";
$l_forum = "อภิปราย ";
$l_forums = "การอภิปราย ";
$l_topic = "หัวข้อเรื่อง ";
$l_topics = "หัวข้อเรื่องทั้งหมด ";
$l_replies = "ตอบกลับ";
$l_poster = "ผู้ส่ง";
$l_author = "ผู้เขียน";
$l_views = "อ่าน";
$l_post = "Post";
$l_posts = "Posts";
$l_message = "ข้อความ ";
$l_messages = "ข้อความทั้งหมด";
$l_subject = "เรื่อง";
$l_from = "จาก";
$l_moderator = "ผู้ดูแล";
$l_username = "๊Username";
$l_password = "รหัสผ่าน";
$l_email = "อีเมล์";
$l_emailaddress = "Email Address";
$l_preferences = "Preferences";
$l_anonymous = "Anonymous";
$l_guest = "Guest";
$l_noposts = "No Posts";
$l_joined = "เข้าร่วม";
$l_gotopage = "ไปที่หน้า";
$l_nextpage = "หน้าต่อไป";
$l_go = "ไป";
$l_selectforum = "เลือก กระดานข่าว";
$l_date = "วันที่";
$l_number = "เลขที่";
$l_name = "ชื่อ";
$l_options = "Options";
$l_submit = "ส่งข้อความ";
$l_confirm = "ยืนยัน";
$l_enter = "ตกลง";
$l_by = "โดย";
$l_ondate = "วัน";
$l_html = "HTML";
$l_bbcode = "BBcode";
$l_smilies = "Smilies";
$l_on = "เปิด";
$l_off = "ปิด";
$l_yes = "ใช่";
$l_no = "ไม่";
$l_click = "Click";
$l_here = "ที่นี่";
$l_toreturn = "กลับไป";
$l_returnindex = "กลับไป to the forum index";
$l_returntopic = "กลับไป to the forum topic list.";
$l_error = "ผิดพลาด";
$l_tryagain = "กรุณาลองใหม่อีกครั้ง";
$l_mismatch = "รหัสผ่านไม่ตรง";
$l_userremoved = "User นี้ถุกลบจากฐานข้อมลูแล้ว";
$l_wrongpass = "คุณพิมพ์รหัสผ่านผิด";
$l_userpass = "โปรดพิมพ์ชื่อผู้ใช้และรหัสผ่าน";
$l_banned = "คุณถูกระงับสิทธิ์ในกระดานข่าวนี้ หากมีข้อสงสัย โปรดติดต่อผู้ดูแลระบบ";
$l_nopost = "คุณไม่ได้รับอนุญาตให้โพสข้อความในกระดานนี้";
$l_noread = "คุณไม่ได้รับอนุญาตให้อ่านข้อความในกระดานนี้";
$l_lastpost = "Post ครั้งล่าสุด";
$l_sincelast = "ตั้งแต่คุณแวะมาครั้งล่าสุด";
$l_newposts = "ใหม่ Posts ตั้งแต่คุณแวะมาครั้งล่าสุด";
$l_nonewposts = "ไม่มี Posts ตั้งแต่คุณแวะมาครั้งล่าสุด";
$l_indextitle = "ดัชนีกระดานข่าว";
$l_profile = "ข้อมูลส่วนตัว";
$l_register = "ลงทะเบียน";
$l_onlyreq = "แก้ไขเท่าที่ต้องการ";
$l_location = "จาก";
$l_viewpostuser = "ดูข้อความของยูสเซอร์นี้";
$l_url = "URL";
$l_icq = "ICQ";
$l_icqnumber = "หมายเลข ICQ ";
$l_icqadd = "เพิ่ม";
$l_icqpager = "เพจเจอร์";
$l_aim = "AIM";
$l_yim = "YIM";
$l_yahoo = "Yahoo Messenger";
$l_msn = "MSN";
$l_messenger = "MSN Messenger";
$l_website = "Web Site Address";
$l_occupation = "อาชีพ";
$l_interests = "ความสนใจ";
$l_signature = "Signature";
$l_sigexplain = "นี่คือกล่องข้อความที่สามารถเพิ่มเติมข้อความได้<BR>สูงสุด 255 ตัวอักษร !";
$l_usertaken = "๊Username ที่คุณเลือกถูกผู้อื่นใช้แล้ว";
$l_infoupdated = "ปรับเปลี่ยนข้อมูลส่วนตัวเรียบร้อย";
$l_publicmail = "อนุญาตให้ผู้อื่นเห็นEmail Address";
$l_itemsreq = "ช่องที่มีเครื่องหมาย * ต้องใส่ข้อมูลให้ครบ";
$l_viewforum = "ดูกระดานข่าว";
$l_notopics = "ไม่มีกระทู้สำหรับกระดานข่าวนี้ คุณสามารถตั้งกระทู้ใหม่ได้";
$l_hotthres = "หัวข้อ Posts";
$l_islocked = "หัวข้อ ล็อค (ไม่มี Posts )";
$l_moderatedby = "ดูแลโดย";
$l_privateforum = "นี้เป็น <b>กระดานส่วนตัว</b>.";
$l_private = "นี้เป็น <b>กระดานส่วนตัว</b>.<br>Note: คุณต้องเปิดคุ๊กกี้ที่เบาร์เซอร์ของคุณ เพื่อสามารถใช้กระดานข่าวส่วนตัวได้";
$l_topictitle = "ดู หัวข้อ";
$l_unregistered = "User ยังไม่ได้ลงทะเบียน";
$l_posted = "Posted";
$l_profileof = "ดูข้อมูลส่วนตัวของ";
$l_viewsite = "ไปที่ Web site ของ";
$l_icqstatus = "ICQ status";
$l_editdelete = "แก้ไข/ลบ Post นี้";
$l_replyquote = "Reply with quote";
$l_viewip = "ดูหมายเลข IP (ผู้ดูแล/ผู้ควบคุมระบบ เท่านั้น)";
$l_locktopic = "ล็อค หัวข้อ นี้";
$l_unlocktopic = "ปลดล็อคหัวข้อ นี้";
$l_movetopic = "ย้าย หัวข้อ นี้";
$l_deletetopic = "ลบ หัวข้อ นี้";
$l_loggedinas = "Logged in as";
$l_notloggedin = "Not logged in";
$l_logout = "Logout";
$l_login = "Login";
$l_separator = ">";
$l_editprofile = "แก้ไขข้อมุลส่วนตัว";
$l_editprefs = "แก้ไข Preferences ของท่าน";
$l_search = "ค้นหา";
$l_memberslist = "รายชื่อสมาชิก";
$l_faq = "FAQ";
$l_privmsgs = "ข้อความ ส่วนตัว";
$l_sendpmsg = "ส่งข้อความส่วนตัว";
$l_adminpanel = "Administration Panel";
$l_poweredby = "Powered by";
$l_version = "Version";
$l_notfilledin = "ผิดพลาด - คุณต้องกรอกข้อมูลให้ครบทุกช่อง";
$l_invalidname = "ชื่อที่เลือก \"\" ถูกผู้อื่นใช้แล้ว";
$l_disallowname = "ชื่อที่เลือก \"\" ถูกสงวนไว้สำหรับผู้ดูแลระบบ";
$l_welcomesubj = "ยินดีต้อนรับสู่กระดานข่าว  ";
$l_welcomemail = "
ยินดีต้อนรับสู่กระดานข่าว  ,

โปรดเก็บอีเมล์ฉบับนี้ไว้ให้ดี


รายละเอียดทะเบียนผู้ใช้ของท่านตามรายการด้านล่างนี้:

----------------------------
Username: 
Password: 
----------------------------

โปรดอย่าลืมรหัสผ่าน เพราะว่ามันถูกเข้ารหัสพิเศษไว้บนฐานข้อมูล และเราไม่สามารถนำมันกลับมาให้ท่านได้อีก
อย่างไรก็ตาม หากกรณีท่านลืมรหัสผ่าน ขอให้ท่านใช้สคริบ เพื่อสุ่มรหัสผ่านใหม่ให้ และส่งให้กับท่านใหม่ทางอีเมล์

ขอบคุณที่ลงทะเบียน


";
$l_beenadded = "ท่านได้ถูกเพิ่มลงในฐานข้อมูลแล้ว";
$l_useruniq = "สมาชิกไม่สามารถใช้ Username ซ้ำกันได้";
$l_storecookie = "เก็บ username ของฉันไว้ในคุ๊กกี้ เป็นเวลา 1 ปี";
$l_prefupdated = "Preferences updated. Click <a href=\"index.\">ที่นี่</a> กลับไป to the forum index";
$l_themecookie = "NOTE: เมื่อต้องการเลือกรูปแบบฉากหลัง คุณต้องเปิดคุ๊กกี้";
$l_alwayssig = "แนบ signature ของฉันด้วยเสมอ";
$l_alwayssmile = "Always disable Smilies";
$l_alwayshtml = "Always disable HTML";
$l_alwaysbbcode = "Always disable BBcode";
$l_boardtheme = "ฉากหลังกระดานข่าว";
$l_nothemes = "ไม่มีฉากหลังในฐานข้อมูล";
$l_saveprefs = "บันทึก Preferences";
$l_searchterms = "Keywords";
$l_searchany = "Search for ANY of the terms (Default)";
$l_searchall = "Search for ALL of the terms";
$l_searchallfrm = "&#3588;&#3657;&#3609;&#3627;&#3634; All Forums";
$l_sortby = "เรียงลำดับโดย";
$l_searchin = "ค้นหาใน";
$l_titletext = "ชื่อเรื่อง & ตัวอักษร";
$l_nomatches = "ไม่มีข้อมูลที่ค้นหา กรุณาเพิ่มเติมข้อมูลสำหรับค้นหา";
$l_whosonline = "Who\'s online?";
$l_nousers = "ไม่มีสมาชิกใดอยู่ในกระดานข่าว";
$l_notedit = "คุณไม่สามารถแก้ไขข้อความนี้ได้";
$l_permdeny = "คุณไม่ได้ให้รหัสผ่าน ที่ถูกต้อง หรือไม่มีสิทธิ์แก้ไขข้อความนี้ กรุณาลองใหม่อีกครั้ง";
$l_editedby = "ข้อความ นี้ ถูกแก้ไขโดย";
$l_stored = "ข้อความ ของท่านได้เก็บไว้ในฐานข้อมูลเรียบร้อย";
$l_viewmsg = "ต้องการดู ข้อความ ของคุณ";
$l_deleted = "Post ถูกลบแล้ว";
$l_nouser = "๊Username ไม่ปรากฎ";
$l_passwdlost = "ฉันลืมรหัสผ่าน!";
$l_delete = "ลบข้อความนี้";
$l_disable = "Disable";
$l_onthispost = "บนข้อความนี้";
$l_htmlis = "HTML คือ";
$l_bbcodeis = "BBcode คือ";
$l_notify = "แจ้งทางอีเมล์ เมื่อมีผู้ตอบหรือส่งข้อความใหม่ ";
$l_emptymsg = "คุณต้องพิมพ์ ข้อความ คุณไม่สามารถส่ง ข้อความ เปล่าได้";
$l_aboutpost = "เกี่ยวกับผู้ส่งข้อความ";
$l_regusers = "เป็น Userที่<b>ลงทะเบียน</b> ทั้งหมด";
$l_anonusers = "<b>Anonymous</b> users";
$l_modusers = "เฉพาะ <B>ผู้ดูแลและAdministrators</b>";
$l_anonhint = "<br>(สามารถส่งข้อความโดยไม่ออกนามได้ โดยไม่ต้องพิมพ์ Usernameและรหัสผ่านเ)";
$l_inthisforum = "สามารถส่งและตอบข้อความบนกระดานข่าวนี้ได้";
$l_attachsig = "แสดง signature <font size=-2>(สามารถเพิ่มได้ในหน้าข้อมูลส่วนตัว)</font>";
$l_cancelpost = "ยกเลิกการส่งข้อความ";
$l_nopostlock = "กระดานข่าวนี้ล็อค ไม่สามารถส่งและตอบข้อความได้";
$l_notifysubj = "A reply to your topic has been posted.";
$l_notifybody = "Dear $m[username]\\r\\nYou are receiving this Email because a message
you posted on $sitename forums has been replied to, and
you selected to be notified on this event.

You may view the topic at:

http://$SERVER_NAME$url_phpbb/viewtopic.$phpEx?topic=$topic&forum=$forum

Or view the $sitename forum index at

http://$SERVER_NAME$url_phpbb

Thank you for using $sitename forums.

Have a nice day.

$email_sig";
$l_norecipient = "You must enter the username you want to send the ข้อความ to.";
$l_sendothermsg = "Send another Private Message";
$l_cansend = "can send ข้อความ ส่วนตัว";
$l_yourname = "Your ๊Username";
$l_recptname = "Recipient ๊Username";
$l_pmposted = "Reply Posted, you can click <a href=\"viewpmsg.\">here</a> to view your ข้อความ ส่วนตัว";
$l_nopmsgs = "คุณไม่มี ข้อความ ส่วนตัว.";
$l_reply = "ตอบ";
$l_deletesucces = "การลบสำเร็จแล้ว";
$l_smilesym = "พิมพ์อะไร";
$l_smileemotion = "อารมณ์";
$l_smilepict = "รูปภาพ";
$l_wrongactiv = "The activation key you provided is not correct. Please check email ข้อความ you recived and make sure you have copied the activation key exactly.";
$l_passchange = "Your password has been successfully changed. You may now goto your <a href=\"bb_profile.?mode=edit\">profile</a> and change your password to a more suitable one.";
$l_wrongmail = "The email address you entered does not match the one stored in our database.";
$l_passsubj = " Forums Password Change";
$l_passsent = "Your password has changed to a new, random, password. Please check your email on how to complete the password change procedure.";
$l_emailpass = "Email Lost Password";
$l_passexplain = "Please fill out the form, a new password will be sent to your Email address";
$l_sendpass = "Send Password";
$langHelp = "ช่วยเหลือ";
$langLastMsgs = "ข้อความล่าสุด";
$l_quotemsg = "[quote]\\nOn $m[post_time], $m[username] wrote:\\n$text\\n[/quote]";
$lang_mail_notification_title = "ตอบในหัวข้อ";
$lang_mail_notification_captatio = "Dear";
$lang_mail_notification_hasreplied = "ตอบกระทู้ถาม";
$lang_mail_notification_ofcourse = "ของวิชา";
$lang_mail_notification_informed = "You stated that you wanted to be informed of replies to this forum message.";
$lang_mail_notification_yesiwant = "Yes, I want to be informed by e-mail (".$_user['mail'].") when a reply is posted";
$lang_reply_this_message = "ตอบข้อความนี้";
$lang_author = "ผู้เขียน";
$lang_threaded_view = "กระทู้ที่ส่งเข้ามา";
$lang_flat_view = "แสดงรายการกระทู้";
$lang_lock = "Lock";
$lang_unlock = "Unlock";
$lang_locked = "ล๊อคแล้ว";
$lang_edit_post = "แก้ไขโพสท์";
$lang_new_topic = "หัวข้อใหม่";
$lang_post_new_topic_in = "หัวข้อใหม่ ใน";
$langLock = "ล็อค";
$langPostNewTopic = "โพสท์หัวข้อใหม่";
?>