<?php /*
for more information: see languages.txt in the lang folder. 
*/
$langLoginBeforePost3  = "đăng nhập vào website";
$langLoginBeforePost2  = "trước tiên bạn cần ";
$langLoginBeforePost1  = "Để gửi bài, ";
$langLastMsg = "Bài gửi gần đây nhất";
$langEditDel = "Sửa/Xoá";
$langSeen = "Đã xem";
$langAdm = "Quản trị diễn đàn";
$langQuote = "Trích dẫn";
$langNewTopic = "Chủ đề mới";
$langAnswer = "Trả lời";
$langGroupSpaceLink = "Không gian nhóm";
$langGroupForumLink = "Diễn đàn nhóm";
$langGroupDocumentsLink = "Tài liệu nhóm ";
$langMyGroup = "nhóm của tôi";
$langOneMyGroups = "giám thị";
$l_body = "Nội dung Bài";
$l_prevpage      = "Trang trước";
$l_new           = "New";
$l_enterpassword = "Phải nhập mật khẩu.";
$l_perday        = "Bài /ngày";
$l_oftotal       = "tổng cộng";
$l_userdisallowed = "The Username you picked has been disallowed by the administrator. Quay lại và thử lần nữa.";
$l_noprivatepost  = "Đây là <b>diễn đàn của thành viên (hạn chế)</b>. Bạn không thể gửi bài vào đây.";
$l_statsblock    = "$statsblock = \"Our users have posted a total of -$total_posts- $l_messages.<br>
We have -$total_users- Registered Users.<br>
The newest Registered User is -<a href=\\\"$profile_url\\\">$newest_user</a>-.<br>
-$users_online- \". ($users_online==1?\"user is\":\"users are\") .\" <a href=\\\"$online_url\\\">currently browsing</a> the forums.<br>\";";
$l_privnotify    = "$privnotify = \"<br>You have $new_message <a href=\\\"$privmsg_url\\\">new private \".($new_message>1?\"messages\":\"message\").\"</a>.\";";
$l_thankregister = "Thank you for registering!";
$l_alwaysdisable = "Always disable";
$l_boardlang     = "Board Language";
$l_topicreview   = "Topic Review";
$l_pwdmessage = "Dear $checkinfo[username],
You are receiving this email because you (or someone pretending to be you)
has requested a passwordchange on $sitename forums. If you believe you have
received this message in error simply delete it and your password will remain
the same.

Your new password as generated by the forums is: $newpw

In order for this change to take effect you must visit this page:

   http://$SERVER_NAME$PHP_SELF?actkey=$key

Once you have visited the page your password will be changed in our database,
and you may login to the profile section and change it as desired.

Thank you for using $sitename Forums

$email_sig";
$l_forum = "Diễn đàn";
$l_forums = "Diễn đàn";
$l_topic = "Chủ đề";
$l_topics = "Chủ đề";
$l_replies = "Trả lời";
$l_poster = "Người gửi";
$l_author = "Người gửi";
$l_views = "Số lượt xem";
$l_post = "Bài gửi";
$l_posts = "Bài gửi";
$l_message = "Bài";
$l_messages = "Bài";
$l_subject = "Subject";
$l_from = "Người gửi";
$l_moderator = "Người điều hành";
$l_username = "Username";
$l_password = "Password";
$l_email = "Email";
$l_emailaddress = "Địa chỉ Email";
$l_preferences = "Preferences";
$l_anonymous = "Vô danh";
$l_guest = "Guest";
$l_noposts = "No Bài gửi";
$l_joined = "Joined";
$l_gotopage = "Đến trang";
$l_nextpage = "Trang kế tiếp";
$l_go = "OK";
$l_selectforum = "Chọn Diễn đàn";
$l_date = "Ngày";
$l_number = "Số";
$l_name = "Tên";
$l_options = "Các tuỳ chọn";
$l_submit = "Submit";
$l_confirm = "Xác nhận";
$l_enter = "Enter";
$l_by = "của";
$l_ondate = "-";
$l_html = "HTML";
$l_bbcode = "BBcode";
$l_smilies = "Smilies";
$l_on = "On";
$l_off = "Off";
$l_yes = "Yes";
$l_no = "No";
$l_click = "Bấm chuột";
$l_here = " tại đây";
$l_toreturn = "để trở về";
$l_returnindex = "để trở về danh mục diễn đàn";
$l_returntopic = "để trở về danh mục chủ đề.";
$l_error = "Error";
$l_tryagain = "Quay lại và thử lần nữa.";
$l_mismatch = "Mật khẩu không khớp.";
$l_userremoved = "Người dùng này đã bị xoá";
$l_wrongpass = "Sai mật khẩu.";
$l_userpass = "Nhập username và password.";
$l_banned = "Bạnn đã bị loại ra khỏi diễn đàn này. Hãy liên hệ với người quản trị.";
$l_nopost = "Không có quyền gửi bài.";
$l_noread = "Không có quyền truy cập.";
$l_lastpost = "Bài gửi gần nhất";
$l_sincelast = "từ lần viếng thăm cuối của bạn";
$l_newposts = "Bài gửi mới từ lần viếng thăm cuối của bạn";
$l_nonewposts = "Không có Bài gửi mới từ lần viếng thăm cuối của bạn";
$l_indextitle = "Trang chủ của diễn đàn";
$l_profile = "Lý lịch";
$l_register = "Đăng ký";
$l_onlyreq = "Chỉ cần thiết nếu đã thay đổi";
$l_location = "của";
$l_viewpostuser = "Xem bài gửi của user này";
$l_url = "URL";
$l_icq = "ICQ";
$l_icqnumber = "ICQ Number";
$l_icqadd = "Add";
$l_icqpager = "Pager";
$l_aim = "AIM";
$l_yim = "YIM";
$l_yahoo = "Yahoo Messenger";
$l_msn = "MSN";
$l_messenger = "MSN Messenger";
$l_website = "Địa chỉ Web Site";
$l_occupation = "Nghề nghiệp";
$l_interests = "Sở thích";
$l_signature = "Chữ ký";
$l_sigexplain = "This is a block of text that can be added to posts you make.<BR>255 characters max!";
$l_usertaken = "The Username you picked has been taken.";
$l_infoupdated = "Your Information has been updated";
$l_publicmail = "Allow other users to view my Địa chỉ Email";
$l_itemsreq = "Items marked with a * are required";
$l_viewforum = "Xem diễn đàn";
$l_notopics = "Chưa có bài viết nào.";
$l_hotthres = "More then  Bài gửi";
$l_islocked = "Chủ đề is Locked (No new Bài gửi may be made in it)";
$l_moderatedby = "Điều hành bởi";
$l_privateforum = "Đây là <b>diễn đàn của thành viên (hạn chế)</b>.";
$l_private = "Đây là <b>diễn đàn của thành viên (hạn chế)</b>.<br>Note: you must have cookies enabled in order to use private forums.";
$l_topictitle = "Xem Chủ đề";
$l_unregistered = "Người dùng chưa đăng ký";
$l_posted = "Ngày";
$l_profileof = "Xem lý lịch của";
$l_viewsite = "Đến thăm website của";
$l_icqstatus = "ICQ status";
$l_editdelete = "Sửa/Xoá Bài gửi này";
$l_replyquote = "Trả lời có trích dẫn";
$l_viewip = "View Posters IP (Moderators/Admins Only)";
$l_locktopic = "Khoá Chủ đề này";
$l_unlocktopic = "Mở khoá Chủ đề này";
$l_movetopic = "Di chuyển Chủ đề này";
$l_deletetopic = "Xoá Chủ đề này";
$l_loggedinas = " ";
$l_notloggedin = "Chưa log in";
$l_logout = "Logout";
$l_login = "Login";
$l_separator = " > ";
$l_editprofile = "Sửa thông tin cá nhân";
$l_editprefs = "Edit Your Preferences";
$l_search = "Search";
$l_memberslist = "Danh sách thành viên";
$l_faq = "Hỏi đáp";
$l_privmsgs = "Bài riêng tư";
$l_sendpmsg = "Send a Private Message";
$l_adminpanel = "Administration Panel";
$l_poweredby = "Powered by";
$l_version = "Version";
$l_notfilledin = "Error - you did not fill in all the required fields.";
$l_invalidname = "The username you chose \"\" has been taken.";
$l_disallowname = "The username you chose, \"\" has been disallowed by the administrator.";
$l_welcomesubj = "Welcome to  Forums";
$l_welcomemail = "
Welcome to  Forums,

Please keep this email for your records.


Your account information is as follows:

----------------------------
Username: 
Password: 
----------------------------

Please do not forget your password as it has been encrypted in our database and we cannot retrieve it for you.
However, should you forget your password we provide an easy to use script to generate and email a new, random, password.

Thank you for registering.


";
$l_beenadded = "You have been added to the database.";
$l_useruniq = "Must be unique. No two users can have the same Username.";
$l_storecookie = "Store my username in a cookie for 1 year.";
$l_prefupdated = "Preferences updated. Bấm chuột <a href=\"index.\"> tại đây</a> để trở về danh mục diễn đàn";
$l_themecookie = "NOTE: In order to use themes you MUST have cookies enabled.";
$l_alwayssig = "Always attach my signature";
$l_alwayssmile = "Always disable Smilies";
$l_alwayshtml = "Always disable HTML";
$l_alwaysbbcode = "Always disable BBcode";
$l_boardtheme = "Board Theme";
$l_nothemes = "No Themes In database";
$l_saveprefs = "Save Preferences";
$l_searchterms = "Keywords";
$l_searchany = "Search for ANY of the terms (Default)";
$l_searchall = "Search for ALL of the terms";
$l_searchallfrm = "Search All Forums";
$l_sortby = "Sort by";
$l_searchin = "Search in";
$l_titletext = "Title & Text";
$l_nomatches = "No records match that query. Please broaden your search.";
$l_whosonline = "Who\'s online?";
$l_nousers = "No Users are currently browsing the forums";
$l_notedit = "You can\'t edit a post that isn\'t yours.";
$l_permdeny = "You did not supply the correct Password or do not have permission to edit this post. Quay lại và thử lần nữa.";
$l_editedby = "This Bài was edited by:";
$l_stored = "Bài của bạn đã được lưu.";
$l_viewmsg = "để xem Bài.";
$l_deleted = "Bài gửi đã bị xoá.";
$l_nouser = "That Username doesn\'t exist.";
$l_passwdlost = "I forgot my password!";
$l_delete = "Delete this Post";
$l_disable = "Disable";
$l_onthispost = "on this Post";
$l_htmlis = "HTML is";
$l_bbcodeis = "BBcode is";
$l_notify = "Notify by email when replies are posted";
$l_emptymsg = "You must type a Bài to post. You cannot post an empty Bài.";
$l_aboutpost = "About Posting";
$l_regusers = "All <b>Registered</b> users";
$l_anonusers = "<b>Anonymous</b> users";
$l_modusers = "Only <B>Moderators and Administrators</b>";
$l_anonhint = "<br>(To post anonymously simply do not enter a username and password)";
$l_inthisforum = "can post new topics and replies to this forum";
$l_attachsig = "Show signature <font size=-2>(This can be altered or added in your profile)</font>";
$l_cancelpost = "Cancel Post";
$l_nopostlock = "You cannot post a reply to this topic, it has been locked.";
$l_notifysubj = "A reply to your topic has been posted.";
$l_notifybody = "Dear $m[username]\\r\\nYou are receiving this Email because a message
you posted on $sitename forums has been replied to, and
you selected to be notified on this event.

You may view the topic at:

http://$SERVER_NAME$url_phpbb/viewtopic.$phpEx?topic=$topic&forum=$forum

Or view the $sitename forum index at

http://$SERVER_NAME$url_phpbb

Thank you for using $sitename forums.

Have a nice day.

$email_sig";
$l_norecipient = "You must enter the username you want to send the Bài to.";
$l_sendothermsg = "Send another Private Message";
$l_cansend = "can send Bài riêng tư";
$l_yourname = "Your Username";
$l_recptname = "Recipient Username";
$l_pmposted = "Reply Posted, you can click <a href=\"viewpmsg.\">here</a> to view your Bài riêng tư";
$l_nopmsgs = "You don\'t have any Bài riêng tư.";
$l_reply = "Reply";
$l_deletesucces = "Deletion successful.";
$l_smilesym = "What to type";
$l_smileemotion = "Emotion";
$l_smilepict = "Picture";
$l_wrongactiv = "The activation key you provided is not correct. Please check email Bài you recived and make sure you have copied the activation key exactly.";
$l_passchange = "Your password has been successfully changed. You may now goto your <a href=\"bb_profile.?mode=edit\">profile</a> and change your password to a more suitable one.";
$l_wrongmail = "The email address you entered does not match the one stored in our database.";
$l_passsubj = " Forums Password Change";
$l_passsent = "Your password has changed to a new, random, password. Please check your email on how to complete the password change procedure.";
$l_emailpass = "Email Lost Password";
$l_passexplain = "Please fill out the form, a new password will be sent to your Email address";
$l_sendpass = "Send Password";
$langHelp = "Help";
?>