<?php /*
for more information: see languages.txt in the lang folder. 
*/
$langLoginBeforePost3  = "въведеш име и парола";
$langLoginBeforePost2  = "предварително трябва да ";
$langLoginBeforePost1  = "Да публикуваш съобщения във форума, ";
$langLastMsg = "Последно съобщение";
$langEditDel = "Редактирай/изтрий";
$langSeen = "Видян";
$langAdm = "Администриране на форумите";
$langQuote = "Quote";
$langNewTopic = "Нова тема";
$langAnswer = "Отговор";
$langGroupSpaceLink = "Group area";
$langGroupForumLink = "Форум на група";
$langGroupDocumentsLink = "Документи на група ";
$langMyGroup = "моята група";
$langOneMyGroups = "my supervision";
$l_body = "Съобщение Body";
$l_prevpage      = "Предишна страница";
$l_new           = "Нов";
$l_enterpassword = "Трябва да си въведете паролата.";
$l_perday        = "Съобщения per day";
$l_oftotal       = "of total";
$l_userdisallowed = "The ПОтребителско име you picked has been disallowed by the administrator. Моля върнете обратно и опитайте отново.";
$l_noprivatepost  = "&#1058;&#1086;&#1074;&#1072; &#1077; <b>&#1063;&#1072;&#1089;&#1090;&#1077;&#1085; &#1060;&#1086;&#1088;&#1091;&#1084;</b>. &#1053;&#1103;&#1084;&#1072;&#1090;&#1077; &#1087;&#1088;&#1072;&#1074;&#1072; &#1079;&#1072; &#1087;&#1080;&#1089;&#1072;&#1085;&#1077; &#1074; &#1085;&#1077;&#1075;&#1086;.";
$l_statsblock    = "$statsblock = \"Our users have posted a total of -$total_posts- $l_messages.<br>
We have -$total_users- Registered Users.<br>
The newest Registered User is -<a href=\\\"$profile_url\\\">$newest_user</a>-.<br>
-$users_online- \". ($users_online==1?\"user is\":\"users are\") .\" <a href=\\\"$online_url\\\">currently browsing</a> the forums.<br>\";";
$l_privnotify    = "$privnotify = \"<br>You have $new_message <a href=\\\"$privmsg_url\\\">new private \".($new_message>1?\"messages\":\"message\").\"</a>.\";";
$l_thankregister = "Thank you for registering!";
$l_alwaysdisable = "Always disable";
$l_boardlang     = "Board Language";
$l_topicreview   = "Topic Review";
$l_pwdmessage = "Dear $checkinfo[username],
You are receiving this email because you (or someone pretending to be you)
has requested a passwordchange on $sitename forums. If you believe you have
received this message in error simply delete it and your password will remain
the same.

Your new password as generated by the forums is: $newpw

In order for this change to take effect you must visit this page:

   http://$SERVER_NAME$PHP_SELF?actkey=$key

Once you have visited the page your password will be changed in our database,
and you may login to the profile section and change it as desired.

Thank you for using $sitename Forums

$email_sig";
$l_forum = "Форим";
$l_forums = "Форуми";
$l_topic = "Тема";
$l_topics = "Теми";
$l_replies = "Отговори";
$l_poster = "Обява";
$l_author = "Автор";
$l_views = "Разглежадания";
$l_post = "Обява";
$l_posts = "Обяви";
$l_message = "Съобщение";
$l_messages = "Съобщения";
$l_subject = "Тема";
$l_from = "От";
$l_moderator = "Moderator";
$l_username = "ПОтребителско име";
$l_password = "Парола";
$l_email = "e-mail";
$l_emailaddress = "Електронен пощенски адрес";
$l_preferences = "Настройки";
$l_anonymous = "Анонимен";
$l_guest = "Гост";
$l_noposts = "No Обяви";
$l_joined = "Joined";
$l_gotopage = "Отиди на страница";
$l_nextpage = "Следваща страница";
$l_go = "Go";
$l_selectforum = "Select a Форим";
$l_date = "Дата";
$l_number = "Брой";
$l_name = "Име";
$l_options = "Опции";
$l_submit = "Submit";
$l_confirm = "Confirm";
$l_enter = "Enter";
$l_by = "от";
$l_ondate = "на";
$l_html = "HTML";
$l_bbcode = "BBcode";
$l_smilies = "Усмивки";
$l_on = "ВКЛ";
$l_off = "ИЗКЛ";
$l_yes = "Да";
$l_no = "Не";
$l_click = "Натисни";
$l_here = "тук";
$l_toreturn = "за да се върнеш";
$l_returnindex = "за да се върнеш в началото на форума";
$l_returntopic = "за да се върнеш в списъка с темите.";
$l_error = "Грешка";
$l_tryagain = "Моля върнете обратно и опитайте отново.";
$l_mismatch = "Паролата не съвпада.";
$l_userremoved = "Този потребител е премахнат от потребителската база данни";
$l_wrongpass = "Въвели сте грешна парола.";
$l_userpass = "Моля въведете потребителско име и парола.";
$l_banned = "Нямате достъп до този форум. Обърнете се към системния администратор ако имате някакви въпроси.";
$l_nopost = "You do not have access to post to this forum.";
$l_noread = "You do not have access to read this forum.";
$l_lastpost = "Last Обява";
$l_sincelast = "since your last visit";
$l_newposts = "New Обяви since your last visit";
$l_nonewposts = "No New Обяви since your last visit";
$l_indextitle = "Forum Index";
$l_profile = "Profile";
$l_register = "Register";
$l_onlyreq = "Only requried if being changed";
$l_location = "From";
$l_viewpostuser = "View posts by this user";
$l_url = "URL";
$l_icq = "ICQ";
$l_icqnumber = "ICQ Number";
$l_icqadd = "Add";
$l_icqpager = "Pager";
$l_aim = "AIM";
$l_yim = "YIM";
$l_yahoo = "Yahoo Messenger";
$l_msn = "MSN";
$l_messenger = "MSN Messenger";
$l_website = "Web Site Address";
$l_occupation = "Occupation";
$l_interests = "Interests";
$l_signature = "Signature";
$l_sigexplain = "This is a block of text that can be added to posts you make.<BR>255 characters max!";
$l_usertaken = "The ПОтребителско име you picked has been taken.";
$l_infoupdated = "Your Information has been updated";
$l_publicmail = "Allow other users to view my Електронен пощенски адрес";
$l_itemsreq = "Items marked with a * are required";
$l_viewforum = "View Forum";
$l_notopics = "There are no topics for this forum. You can post one.";
$l_hotthres = "More then  Обяви";
$l_islocked = "Тема is Locked (No new Обяви may be made in it)";
$l_moderatedby = "Moderated by";
$l_privateforum = "This is a <b>Private Forum</b>.";
$l_private = "This is a <b>Private Forum</b>.<br>Note: you must have cookies enabled in order to use private forums.";
$l_topictitle = "View Тема";
$l_unregistered = "Unregistered User";
$l_posted = "Posted";
$l_profileof = "View Profile of";
$l_viewsite = "Goto the website of";
$l_icqstatus = "ICQ status";
$l_editdelete = "Edit/Delete This Обява";
$l_replyquote = "Reply with quote";
$l_viewip = "View Posters IP (Moderators/Admins Only)";
$l_locktopic = "Lock this Тема";
$l_unlocktopic = "Unlock this Тема";
$l_movetopic = "Move this Тема";
$l_deletetopic = "Delete this Тема";
$l_loggedinas = "Logged in as";
$l_notloggedin = "Not logged in";
$l_logout = "Logout";
$l_login = "Login";
$l_separator = "» »";
$l_editprofile = "Edit Profile";
$l_editprefs = "Edit Your Настройки";
$l_search = "Search";
$l_memberslist = "Memberslist";
$l_faq = "FAQ";
$l_privmsgs = "Private Съобщения";
$l_sendpmsg = "Send a Private Message";
$l_adminpanel = "Administration Panel";
$l_poweredby = "Powered by";
$l_version = "Version";
$l_notfilledin = "Error - you did not fill in all the required fields.";
$l_invalidname = "The username you chose \"\" has been taken.";
$l_disallowname = "The username you chose, \"\" has been disallowed by the administrator.";
$l_welcomesubj = "Welcome to  Forums";
$l_welcomemail = "
Welcome to  Forums,

Please keep this email for your records.


Your account information is as follows:

----------------------------
Username: 
Password: 
----------------------------

Please do not forget your password as it has been encrypted in our database and we cannot retrieve it for you.
However, should you forget your password we provide an easy to use script to generate and email a new, random, password.

Thank you for registering.


";
$l_beenadded = "You have been added to the database.";
$l_useruniq = "Must be unique. No two users can have the same Username.";
$l_storecookie = "Store my username in a cookie for 1 year.";
$l_prefupdated = "Настройки updated. Натисни <a href=\"index.\">тук</a> за да се върнеш в началото на форума";
$l_themecookie = "NOTE: In order to use themes you MUST have cookies enabled.";
$l_alwayssig = "Always attach my signature";
$l_alwayssmile = "Always disable Усмивки";
$l_alwayshtml = "Always disable HTML";
$l_alwaysbbcode = "Always disable BBcode";
$l_boardtheme = "Board Theme";
$l_nothemes = "No Themes In database";
$l_saveprefs = "Save Настройки";
$l_searchterms = "Keywords";
$l_searchany = "Search for ANY of the terms (Default)";
$l_searchall = "Search for ALL of the terms";
$l_searchallfrm = "Search All Forums";
$l_sortby = "Sort by";
$l_searchin = "Search in";
$l_titletext = "Title & Text";
$l_nomatches = "No records match that query. Please broaden your search.";
$l_whosonline = "Who\'s online?";
$l_nousers = "No Users are currently browsing the forums";
$l_notedit = "You can\'t edit a post that isn\'t yours.";
$l_permdeny = "You did not supply the correct Парола or do not have permission to edit this post. Моля върнете обратно и опитайте отново.";
$l_editedby = "This Съобщение was edited by:";
$l_stored = "Your Съобщение has been stored in the database.";
$l_viewmsg = "to view your Съобщение.";
$l_deleted = "Your Обява has been deleted.";
$l_nouser = "That ПОтребителско име doesn\'t exist.";
$l_passwdlost = "I forgot my password!";
$l_delete = "Delete this Post";
$l_disable = "Disable";
$l_onthispost = "on this Post";
$l_htmlis = "HTML is";
$l_bbcodeis = "BBcode is";
$l_notify = "Notify by email when replies are posted";
$l_emptymsg = "You must type a Съобщение to post. You cannot post an empty Съобщение.";
$l_aboutpost = "About Posting";
$l_regusers = "All <b>Registered</b> users";
$l_anonusers = "<b>Anonymous</b> users";
$l_modusers = "Only <B>Moderators and Administrators</b>";
$l_anonhint = "<br>(To post anonymously simply do not enter a username and password)";
$l_inthisforum = "can post new topics and replies to this forum";
$l_attachsig = "Show signature <font size=-2>(This can be altered or added in your profile)</font>";
$l_cancelpost = "Cancel Post";
$l_nopostlock = "You cannot post a reply to this topic, it has been locked.";
$l_notifysubj = "A reply to your topic has been posted.";
$l_notifybody = "Dear $m[username]\\r\\nYou are receiving this Email because a message
you posted on $sitename forums has been replied to, and
you selected to be notified on this event.

You may view the topic at:

http://$SERVER_NAME$url_phpbb/viewtopic.$phpEx?topic=$topic&forum=$forum

Or view the $sitename forum index at

http://$SERVER_NAME$url_phpbb

Thank you for using $sitename forums.

Have a nice day.

$email_sig";
$l_norecipient = "You must enter the username you want to send the Съобщение to.";
$l_sendothermsg = "Send another Private Message";
$l_cansend = "can send Private Съобщения";
$l_yourname = "Your ПОтребителско име";
$l_recptname = "Recipient ПОтребителско име";
$l_pmposted = "Reply Posted, you can click <a href=\"viewpmsg.\">here</a> to view your Private Съобщения";
$l_nopmsgs = "You don\'t have any Private Съобщения.";
$l_reply = "Reply";
$l_deletesucces = "Deletion successful.";
$l_smilesym = "What to type";
$l_smileemotion = "Emotion";
$l_smilepict = "Picture";
$l_wrongactiv = "The activation key you provided is not correct. Please check email Съобщение you recived and make sure you have copied the activation key exactly.";
$l_passchange = "Your password has been successfully changed. You may now goto your <a href=\"bb_profile.?mode=edit\">profile</a> and change your password to a more suitable one.";
$l_wrongmail = "The email address you entered does not match the one stored in our database.";
$l_passsubj = " Forums Password Change";
$l_passsent = "Your password has changed to a new, random, password. Please check your email on how to complete the password change procedure.";
$l_emailpass = "Email Lost Password";
$l_passexplain = "Please fill out the form, a new password will be sent to your Email address";
$l_sendpass = "Send Password";
$langHelp = "Help";
$langLastMsgs = "Последно съобщение";
$l_quotemsg = "&#1057;&#1098;&#1086;&#1073;&#1097;&#1077;&#1085;&#1080;&#1077;";
$lang_mail_notification_title = "отговор по темата";
$lang_mail_notification_captatio = "Скъпи";
$lang_mail_notification_hasreplied = "отговори на съобщение във форума";
$lang_mail_notification_ofcourse = "на курса";
$lang_mail_notification_informed = "Вие сте заявили, че искате да бъдете информиран за отговорите на това съобщение във форума.";
$lang_mail_notification_yesiwant = "Да, аз искам да ме информират с е-майл (".$_user['mail'].") когато постъпи отговор";
$lang_reply_this_message = "Отговор на това съобщение";
$lang_author = "Автор";
$lang_threaded_view = "Преглед по нишки";
$lang_flat_view = "Прост преглед";
$lang_lock = "Заключване";
$lang_unlock = "Отключване";
$lang_locked = "заключен";
$lang_edit_post = "Редактиране на съобщението";
$lang_new_topic = "Нова тема";
$lang_post_new_topic_in = "Нова тема в";
$langLock = "Заключване";
$langPostNewTopic = "&#1047;&#1072;&#1087;&#1086;&#1095;&#1085;&#1080; &#1085;&#1086;&#1074;&#1072; &#1090;&#1077;&#1084;&#1072;";
?>